# Generated by Django 5.1.4 on 2025-01-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
