# Generated by Django 5.1.4 on 2025-01-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e1', '0002_course_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
